#!/bin/bash

BASENAME=$(basename "$0")

function die() {
    echo "${BASENAME}: $*" >&2
    exit 1
}

function usage() {
    echo "Usage: ${BASENAME} daydir" >&2
    exit 2
}

[[ $# -eq 1 ]] || usage

YEAR=2025

DAYDIR="$1"
[[ -d "${DAYDIR}" ]] && die "daydir ${DAYDIR} already exists"

[[ -d tpl ]] || die "tpl doesn't exist"

if [[ ! -x ../utils/get_input ]] ; then
	pushd ../utils
	make || die "failed to build utils"
	popd
fi

mkdir -p "${DAYDIR}" || die "failed to make ${DAYDIR}"

for tpl_path in tpl/*; do
    f=$(basename "$tpl_path")

    if [[ ${f} = dot.* ]]; then
	dest="${DAYDIR}/${f#dot}"
    else
	dest="${DAYDIR}"
    fi

    echo cp -R "${tpl_path}" "${dest}"
    cp -R "${tpl_path}" "${dest}" || die "failed to copy"
done

bazel run :gazelle_fix
bazel test "${DAYDIR}/..."

../utils/get_input \
	--session_file ~/keys/aoc_session_cookie \
	--year ${YEAR} \
	--day $(echo ${DAYDIR} |sed -e 's/^0//') \
	>${DAYDIR}/input.txt || die "failed to get input"
