#!/bin/bash

BASENAME=$(basename "$0")

function die() {
    echo "${BASENAME}: $*" >&2
    exit 1
}

function usage() {
    echo "Usage: ${BASENAME} daydir" >&2
    exit 2
}

[[ $# -eq 1 ]] || usage

DAYDIR="$1"
[[ -d "${DAYDIR}" ]] && die "daydir ${DAYDIR} already exists"

[[ -d ../tpl ]] || die "../tpl doesn't exist"

mkdir -p "${DAYDIR}"/src || die "failed to make ${DAYDIR}/src"

for tpl_path in ../tpl/*; do
    f=$(basename "$tpl_path")

    if [[ ${f} = dot.* ]]; then
	dest="${DAYDIR}/${f#dot}"
    else
	dest="${DAYDIR}"
    fi

    echo cp "${tpl_path}" "${dest}"
    cp "${tpl_path}" "${dest}" || die "failed to copy"
done
